#!/bin/sh

if [ "$DEBUG" -gt 0 ]; then
	echo "(t) Shuting down openttd...\n"
fi

PID=`ps ax | grep "openttd" | grep -v grep | awk {'print $1'}`

if [ "$DEBUG" -gt 0 ]; then
	echo "Openttd runs with PID: $PID \n"
fi

if `kill -3 $PID`; then
        echo "Success!"
	while `/bin/ps -axg | grep -v grep | grep /usr/games/openttd > /dev/null`; do echo "wait for openttd" sleep 5; done
        exit 0
else
        echo "Fail! $?"
        exit 111
fi
